export type UPDATE_GREETING = "UPDATE_GREETING";
export type INCREMENT = "INCREMENT";
export type UPDATE_TOKEN = "UPDATE_TOKEN";
export type UPDATE_USER = "UPDATE_USER";

export const UPDATE_GREETING: UPDATE_GREETING = "UPDATE_GREETING";
export const INCREMENT: INCREMENT = "INCREMENT";
export const UPDATE_TOKEN: UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_USER: UPDATE_USER = "UPDATE_USER";
