export type UPDATE_GREETING = "UPDATE_GREETING";
export type INCREMENT = "INCREMENT";
export type UPDATE_TOKEN = "UPDATE_TOKEN";
export type UPDATE_USER = "UPDATE_USER";
export type UPDATE_GISTS = "UPDATE_GISTS";
export type DELETE_GIST = "DELETE_GIST";
export type CREATE_GIST = "CREATE_GIST";

export const UPDATE_GREETING: UPDATE_GREETING = "UPDATE_GREETING";
export const INCREMENT: INCREMENT = "INCREMENT";
export const UPDATE_TOKEN: UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_USER: UPDATE_USER = "UPDATE_USER";
export const DELETE_GIST: DELETE_GIST = "DELETE_GIST";
export const UPDATE_GISTS: UPDATE_GISTS = "UPDATE_GISTS";
export const CREATE_GIST: CREATE_GIST = "CREATE_GIST";
